const ENGLISH_PREMIER_LEAGUE = 'ENGLISH_PREMIER_LEAGUE';
const GERMAN_1_BUNDESLIGA = 'GERMAN_1_BUNDESLIGA';
const SPANISH_PRIMERA = 'SPANISH_PRIMERA';
const ITALIAN_SERIE_A = 'ITALIAN_SERIE_A';
const FRENCH_LEAGUE_1 = 'FRENCH_LEAGUE_1';

const LEAGUES = {
  [ENGLISH_PREMIER_LEAGUE]: 'English Premier League',
  [GERMAN_1_BUNDESLIGA]: 'German 1.Bundesliga',
  [SPANISH_PRIMERA]: 'Spanish Primera',
  [ITALIAN_SERIE_A]: 'Italian Serie A',
  [FRENCH_LEAGUE_1]: 'French League 1'
};

export {
  ENGLISH_PREMIER_LEAGUE,
  GERMAN_1_BUNDESLIGA,
  SPANISH_PRIMERA,
  ITALIAN_SERIE_A,
  FRENCH_LEAGUE_1,
  LEAGUES
};
